### ISSUE TITLE
Compile error on Arch Linux

### ISSUE THREAD

**Issue by arcmags** [valiant1x/intensecoin#64] opened 2018-04-18 17:09 UTC
Unable to build current release (and previous releases) of intensecoin on Arch Linux.

Current packages:
```boost 1.66.0-2
boost-libs 1.66.0-2
cmake 3.10.3-1
expat 2.2.5-1
gcc 7.3.1+20180312-2
gcc-libs 7.3.1+20180312-2
gcc6 6.4.1-5
gcc6-libs 6.4.1-5
gtest 1.8.0-1
ldns 1.7.0-4
lib32-gcc-libs 7.3.1+20180312-2
lib32-openssl 1:1.1.0.h-1
libunwind 1.2.1-1
linux 4.15.15-1
miniupnpc 2.0.20180406-1
openssl 1.1.0.h-1
openssl-1.0 1.0.2.o-1
pkg-config 0.29.2-1
unbound 1.7.0-1
xz 5.2.3-1
```

Error: 

```mkdir -p build/release
cd build/release && cmake -D BUILD_TESTS=ON -D CMAKE_BUILD_TYPE=release ../.. && make
-- The C compiler identification is GNU 7.3.1
-- The CXX compiler identification is GNU 7.3.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Building without build tag
-- Could not find DEVELOPER_LOCAL_TOOLS in env (not required)
-- BOOST_IGNORE_SYSTEM_PATHS defaults to OFF
-- Could not find DEVELOPER_LIBUNBOUND_OLD in env (not required)
-- Building for a 64-bit system
-- Building internal libraries as static
-- Could not find DATABASE in env (not required unless you want to change database type from default: lmdb)
-- Using LMDB as default DB type
-- Stack trace on exception enabled
-- Found OpenSSL: /usr/lib/libcrypto.so (found version "1.1.0h") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Found MiniUPnPc: /usr/include/miniupnpc  
-- Found miniupnpc API version 17
-- Using shared miniupnpc found at /usr/include/miniupnpc
-- Looking for libunbound
-- Found libunbound include (unbound.h) in /usr/include
-- Found libunbound shared library
-- Using 64-bit LMDB from source tree
-- Building on x86_64 for native
-- AES support enabled
-- Found Boost Version: 106600
-- Looking for rl_copy_text
-- Looking for rl_copy_text - found
-- Looking for rl_filename_completion_function
-- Looking for rl_filename_completion_function - found
-- Found readline library at: /usr
-- Found Git: /usr/bin/git
-- Found GTest: /usr/lib/libgtest.so  
Doxygen: graphviz not found - graphs disabled
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Configuring done
-- Generating done

.
.
.

[ 64%] Linking CXX executable transaction_fuzz_tests
../../src/cryptonote_basic/libcryptonote_basic.a(cryptonote_format_utils.cpp.o): In function `cryptonote::generate_genesis_block(cryptonote::block&)':
cryptonote_format_utils.cpp:(.text+0x8561): undefined reference to `cryptonote::construct_miner_tx(unsigned long, unsigned long, unsigned long, unsigned long, unsigned long, cryptonote::account_public_address const&, cryptonote::transaction&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long, unsigned char)'
collect2: error: ld returned 1 exit status
make[3]: *** [tests/fuzz/CMakeFiles/transaction_fuzz_tests.dir/build.make:150: tests/fuzz/transaction_fuzz_tests] Error 1```

**Comment by valiant1x** [comment] 2018-04-18 18:34
duplicate of #59 

it would appear tests are being built. run `make clean` then `make release`

**Comment by arcmags** [comment] 2018-04-19 02:46
Compiled successfully via `make clean` and `make release`.

**Comment by valiant1x** [comment] 2018-04-19 02:57
we are continuing work in #59 to resolve the broken tests.

**Closed by valiant1x** 2018-04-19 02:57 UTC
