### ISSUE TITLE
Intensecoind pr1430 sync problem

### ISSUE THREAD

**Issue by vojcha** [valiant1x/intensecoin#33] opened 2018-02-05 16:19 UTC
Hello,

I started intensecoind but it wont start synchronization. Meanwhile i created wallet address and send some coins on it but now i don't know how i can receive these coins.
here are some details on the screenshot: https://i.snag.gy/mTPBsU.jpg
Are these coins lost or there are some possible solution?

**Comment by vojcha** [comment] 2018-02-06 09:43
[intensecoin.log](https://github.com/valiant1x/intensecoin/files/1698490/intensecoin.log)
Maybe this log file can help

**Comment by valiant1x** [comment] 2018-02-08 14:27
You're using an out of date binary, download the latest from https://github.com/valiant1x/intensecoin/releases/download/1.4.3/Intensecoin-daemon-win64-pr1430.zip

duplicate of #28 #32

**Comment by vojcha** [comment] 2018-02-08 20:46
Thank you,

It now works well but wallet balance is still zero although pool sent some coins to it. Here is the list of all transactions:

[e0913a651df78c0eac290cb4b0ab66984a007d2208ccf0f7e6506729d2ae032f](http://intensecoin.com/explorer/#blockchain_transaction?hash=e0913a651df78c0eac290cb4b0ab66984a007d2208ccf0f7e6506729d2ae032f)
[66e048fb884c1a57a1a1e0d41ec8bfe1a00736bf78a365640dcbc7987c75a8d5](http://intensecoin.com/explorer/#blockchain_transaction?hash=66e048fb884c1a57a1a1e0d41ec8bfe1a00736bf78a365640dcbc7987c75a8d5)
[0971a1733dcd0051f7ead7464f3449caf3b84c39c3c62872eb2dff538159fc3d](http://intensecoin.com/explorer/#blockchain_transaction?hash=0971a1733dcd0051f7ead7464f3449caf3b84c39c3c62872eb2dff538159fc3d)
[f3a15238865dc05d63bcd08bb5cf5da024fa6afdb4877b22d3880c36c0e02f42](http://intensecoin.com/explorer/#blockchain_transaction?hash=f3a15238865dc05d63bcd08bb5cf5da024fa6afdb4877b22d3880c36c0e02f42)
[f94b03309a99862f7196ba121a68cbcd7e282fe4fb64ff17c67ea6071e1ff614](http://intensecoin.com/explorer/#blockchain_transaction?hash=f94b03309a99862f7196ba121a68cbcd7e282fe4fb64ff17c67ea6071e1ff614)
[aadaaf5eabdb8f406759ab860e2f1a5528ac60303e92922f534ce6ed501ab4f9](http://intensecoin.com/explorer/#blockchain_transaction?hash=aadaaf5eabdb8f406759ab860e2f1a5528ac60303e92922f534ce6ed501ab4f9)
[8576eafb6d3dc1f69098c396b6a65ea0ab664fd4e57ee64170b5fd04fc4f16d1](http://intensecoin.com/explorer/#blockchain_transaction?hash=8576eafb6d3dc1f69098c396b6a65ea0ab664fd4e57ee64170b5fd04fc4f16d1)
[63653dd9dd88f48b8a0a0b1edc9e66c53d8bbcd7302538b4dfa7c547ba528028](http://intensecoin.com/explorer/#blockchain_transaction?hash=63653dd9dd88f48b8a0a0b1edc9e66c53d8bbcd7302538b4dfa7c547ba528028)
[d273b610752341b212c92e2af43a1994a38a53843d0038786e0ef7c53d8c8713](http://intensecoin.com/explorer/#blockchain_transaction?hash=d273b610752341b212c92e2af43a1994a38a53843d0038786e0ef7c53d8c8713)
[38a336ad89b0a8a75e0b219af3c9d69a289b2bd62d47b6d37db390946530522d](http://intensecoin.com/explorer/#blockchain_transaction?hash=38a336ad89b0a8a75e0b219af3c9d69a289b2bd62d47b6d37db390946530522d)
[7e951acbb969105a1bcf0c8df67377cec143aa8876a7e26d16ca194dec8453b2](http://intensecoin.com/explorer/#blockchain_transaction?hash=7e951acbb969105a1bcf0c8df67377cec143aa8876a7e26d16ca194dec8453b2)
[1798fc8c6197d441e0df18dd775bdd786a4307e52a06fd60d4774cc5ed8cc765](http://intensecoin.com/explorer/#blockchain_transaction?hash=1798fc8c6197d441e0df18dd775bdd786a4307e52a06fd60d4774cc5ed8cc765)
[16de60d797d98f4abc416fd2765092c6bc23cd365081925a0528e5ee3a0e81dc](http://intensecoin.com/explorer/#blockchain_transaction?hash=16de60d797d98f4abc416fd2765092c6bc23cd365081925a0528e5ee3a0e81dc)
[3874b007986c813fbabc51ae2e13f9b2f0c7ae108653ff5ee263b97df332e2c1](http://intensecoin.com/explorer/#blockchain_transaction?hash=3874b007986c813fbabc51ae2e13f9b2f0c7ae108653ff5ee263b97df332e2c1)

can you do something to get those coins on my wallet?

**Comment by valiant1x** [comment] 2018-02-09 04:22
try `rescan_bc` in intense-wallet-cli. does the wallet produce any errors or complaints about daemon connectivity? what is the output of `status` in the wallet?

**Comment by vojcha** [comment] 2018-02-09 19:27
Hello,

I already treid `rescan_bc` but it didn't help.

About the status here is what its showing:

![](https://i.snag.gy/uTbHzg.jpg)

**Comment by vojcha** [comment] 2018-02-11 22:46
![image](https://user-images.githubusercontent.com/36165316/36079642-b00619e8-0f85-11e8-9af8-6f0dcf054652.png)

**Comment by valiant1x** [comment] 2018-02-15 02:13
to resolve your issue, restore your wallet (create a new one) using the word seed or the private keys. the wallet you referenced was created in 1.44.0 or earlier, which had a bug that caused wallets generated while the daemon was offline to have too high of a height it began scanning the blockchain for txs.

**Closed** 2018-02-15 02:14 UTC
Labels: duplicate
