### ISSUE TITLE
So I downloaded 1.4.2prelease and mined to an wallet created with 1.4.2

### ISSUE THREAD

**Issue by reneliust** [valiant1x/intensecoin#28] opened 2018-01-22 12:59 UTC
Then I realized I could not access my mined itns. The intensecoind.exe is not syncing with the main chain. I tried to restore the CLI created wallet with 1.4.1 simplewallet.exe and gui wallet. Both return wrong password. 
What are my solution options?  Would waiting for 1.4.2 going online help? I do have the 25 words and private keys, is that possible to restore the wallet on 1.4.1 wallet?

**Comment by reneliust** [comment] 2018-01-22 14:36
1.4.2 intensecoind.exe sees the blockchain at height 1 and seems not on the main chain

**Comment by reneliust** [comment] 2018-01-22 15:29
![default](https://user-images.githubusercontent.com/35691798/35228628-1af2359e-ffcc-11e7-9ef6-43b25e07dcbc.png)

**Comment by reneliust** [comment] 2018-01-23 09:39
blockchain import failed,here is the screenshot 
![default](https://user-images.githubusercontent.com/35691798/35267898-ab48fd3a-0062-11e8-95b5-aa384f695627.png)

I checked my firewall and router and switched to other computers and isps to rule out a network problem and I believe this is not a network issue. My others version intensecoind daemons and etn xmr daemons are runing fine. 

Actually 1.4.2 intensecoind daemons are connected to six main nodes in the following screesshot
![default](https://user-images.githubusercontent.com/35691798/35268216-78faf738-0063-11e8-816d-53bd6a59a00a.png)

Could u please just test run 1.4.2 intensecoind.exe in a new computer to see how it works?

I need a vpn which is quite unreliable to use bitcointalk so I post the details here.  Thanks

**Comment by valiant1x** [comment] 2018-01-25 04:56
The blockchain-import tool was updated in 1.4.2.1 to permit import of the larger block sizes found in ITNS, please update to the latest pre-release version and let me know if that works for you. I also updated some internal checkpoints that may have been preventing you from syncing.

**Comment by reneliust** [comment] 2018-01-25 09:16
So i tested 1.4.2.1: From fresh start the daemon still sees height:1 target:1
Then I imported the blockchain you uploaded, this time the import's successful. However,  the daemon cannot see beyond the height from the imported chain. 
Screenshot:
![default](https://user-images.githubusercontent.com/35691798/35380177-82423c66-01f3-11e8-9d18-4e16a8d2252e.png)

**Comment by valiant1x** [comment] 2018-01-25 15:47
please:
1. clear the intensecoind.log file from `C:\ProgramData\intensecoin`
2. run the daemon with `--log-level 3` for a few minutes 
3. upload the full intensecoind.log

**Comment by reneliust** [comment] 2018-01-25 18:06
[intensecoin.log](https://github.com/valiant1x/intensecoin/files/1665104/intensecoin.log)

**Comment by valiant1x** [comment] 2018-01-25 19:35
There is not much to surmise from those logs other than the peers are being attempted for connection, but your machine or network is failing. This message is recurring:
```
2018-01-25 17:51:39.427	[P2P9]	TRACE	net	contrib/epee/include/net/abstract_tcp_server2.inl:342	[sock 664] Some not success at read: End of file:2
2018-01-25 17:51:40.554	[P2P9]	TRACE	net	contrib/epee/include/net/abstract_tcp_server2.inl:98	[sock 656] Socket destroyed
```
I was able to run the daemon on another machine, and it worked fine after allowing Intensecoind to access the internet from Windows Firewall.

This still appears to be a localized network issue for you

**Comment by reneliust** [comment] 2018-01-25 20:40
It's weird. Do you have a remote daemon node? I'll just skip running local daemon.

**Comment by valiant1x** [comment] 2018-01-26 03:04
Any of the seed nodes should be appropriate:
```
          full_addrs.insert("192.124.18.154:48772");
          full_addrs.insert("104.200.65.202:48772");
          full_addrs.insert("45.32.171.89:48772");
	  full_addrs.insert("45.63.69.34:48772");
	  full_addrs.insert("62.48.164.61:48772");
	  full_addrs.insert("35.205.108.96:48772");
	  full_addrs.insert("195.154.133.155:48772");
	  full_addrs.insert("69.162.83.203:48772");
	  full_addrs.insert("111.231.72.116:48772");
```

**Comment by valiant1x** [comment] 2018-01-26 03:11
On re-examination of your log file I notice this line:
`2018-01-25 17:50:45.190	660	WARN 	blockchain.db.lmdb	src/blockchain_db/lmdb/db_lmdb.cpp:72	Error attempting to retrieve a hard fork version at height 0 from the db: MDB_NOTFOUND: No matching key/data pair found`

Are you absolutely positive that you are cleanly deleting the entire data directory (C:\ProgramData\intensecoin) when attempting to sync from scratch?

**Comment by reneliust** [comment] 2018-01-26 03:17
Yes, I shift-deleted C:\programdata\intensecoin many times. I will try connect cli client to seed nodes directly.

**Comment by valiant1x** [comment] 2018-01-26 03:19
You can also try running `intensecoind --db-salvage` but it looks like even the genesis block is either not generating correctly or not being serialized to the database correctly

**Comment by reneliust** [comment] 2018-01-26 03:24
cli reported unable to connect to remote node. I tried two nodes
![default](https://user-images.githubusercontent.com/35691798/35423900-63e1f732-028b-11e8-8a11-015cca3575b5.png)
intensecoind --db-salvage  not working either. 
again, weird  :)

**Comment by valiant1x** [comment] 2018-02-04 21:22
should be resolved by df7159c. [Windows release](https://github.com/valiant1x/intensecoin/releases/tag/1.4.3) was updated, please test and let me know if issues persist

**Comment by reneliust** [comment] 2018-02-06 11:39
Problem solved! Thank you. Looks like I found a major bug:)

**Comment by reneliust** [comment] 2018-02-06 16:27
However, my 1231 intense coins are not in the wallet after full sync.  I do not have the tx id now because hashvault pool has cleared the stats database.  wallet: iz4cJG9CgoSThE9x66Vn1NeZoVpCr2i1CAkn1Uyvfu9KTuSiD2Khu1f47F8yUw1iWG2fTXbEfNf4XNdfSYrS87wz32N5Ux4xM

**Comment by valiant1x** [comment] 2018-02-07 15:51
you can try using `rescan_bc` in the CLI wallet but there is no reason the funds would not be showing up if they were sent to that address. you can also try a simple test send of 0.1 ITNS or so from another wallet.

**Comment by reneliust** [comment] 2018-02-08 16:00
valiant1x, could u send 0.1 itns to the above address? I havent mined itns since. Today I did rescan_bc but nothing came out.
![default](https://user-images.githubusercontent.com/35691798/35983035-2ab59256-0d2c-11e8-9222-b47b7baf8801.png)

**Comment by valiant1x** [comment] 2018-02-09 04:23
the fact that it says `blocks received: 0` indicates it is not communicating correctly with the daemon.

are you certain that `intensecoind` from the XMR rebase, NOT the pre-rebase daemon or the GUI ITNS wallet, is running?

what is the output of `status` in the wallet?

**Comment by reneliust** [comment] 2018-02-09 09:57
It says blocks received:0 is because it's already fully synced to the daemon. Here is the status output
![default](https://user-images.githubusercontent.com/35691798/36022071-aff8cec4-0dc2-11e8-8b2a-0d593e0b082d.png)

**Comment by vojcha** [comment] 2018-02-11 20:56
Anything new about this issue?...i am waiting for the solution too #33

**Comment by valiant1x** [comment] 2018-02-11 21:35
i just created a new wallet and sent it some coins to ensure it is working, and i did receive the coins as expected. i also just sent your wallet iz4cJG9CgoSThE9x66Vn1NeZoVpCr2i1CAkn1Uyvfu9KTuSiD2Khu1f47F8yUw1iWG2fTXbEfNf4XNdfSYrS87wz32N5Ux4xM 0.00000001 coins ([block explorer](http://intensecoin.com/explorer/#blockchain_transaction?hash=d666481b1fa786f1d43cafc13fb05b311c898c35555d95439c1f2fc21f940091)). did you receive the coins?

please provide a screenshot showing `rescan_bc` being run (to analyze the output)
please also watch the daemon after this happens - are any errors shown?

**Comment by vojcha** [comment] 2018-02-12 11:25
Nothing changed with the latest release
![image](https://user-images.githubusercontent.com/36165316/36094679-788347ce-0fef-11e8-85c3-b64ac9ecf322.png)

When you said "resyncing blockchain" did you mean to download it again and not to load it from blockchain.raw file?

**Comment by valiant1x** [comment] 2018-02-12 17:59
Resync meaning clear your data directory, which is c:/ProgramData/intensecoin in the rebase, and resync using either the blockchain.raw or the network. Whichever method you prefer.

**Comment by oldschoola41** [comment] 2018-02-13 22:36
Which pool did you use to mine?

**Comment by vojcha** [comment] 2018-02-14 20:18
![image](https://user-images.githubusercontent.com/36165316/36225829-3b1a1c3a-11cc-11e8-8927-c72e584f3d27.png)
Unfortunately i still haven't got my coins. Is there some other solution? #33

**Comment by vojcha** [comment] 2018-02-14 21:24
I downloaded and installed the latest release 1.44.1 but it didn't fix the problem for me...I still have zero balance in my wallet #33 
![image](https://user-images.githubusercontent.com/36165316/36228881-bb9d432e-11d5-11e8-81c9-7792d54e207c.png)

**Comment by valiant1x** [comment] 2018-02-15 02:13
to resolve your issue, restore your wallet (create a new one) using the word seed or the private keys. the wallet you referenced was created in 1.44.0 or earlier, which had a bug that caused wallets generated while the daemon was offline to have too high of a height it began scanning the blockchain for txs.

**Comment by vojcha** [comment] 2018-02-15 10:48
It took some time and effort but finally i got my coins.

Thank you @valiant1x for the support.

**Comment by valiant1x** [comment] 2018-02-15 15:35
glad you're sorted, i apologize it took so long to get things proper but the issue was not reproducible by us until only recently

**Closed by valiant1x** 2018-02-15 15:35 UTC
Labels: bug
