### ISSUE TITLE
Can't sync past 148673, "Failed to parse block from blob"

### ISSUE THREAD

**Issue by Venthos** [valiant1x/intensecoin#50] opened 2018-03-20 11:47 UTC
Potentially related to Issue #45.

Multiple reports have come in that this is affecting everyone using the XMR Rebase tools, including with the recent patch that addressed Issue 45 already applied.  This seems different.

The only current workaround is to revert to 1.4.1/1.4.2 tools and use them for now.

General output as seen from when my workstation when to sync this morning:

`2018-03-19 16:54:29.733	[P2P5]	INFO 	global	src/cryptonote_protocol/cryptonote_protocol_handler.inl:1521	SYNCHRONIZED OK
2018-03-20 11:12:24.294	[P2P5]	INFO 	global	src/cryptonote_protocol/cryptonote_protocol_handler.inl:305	[92.14.239.76:48772 OUT] Sync data returned a new top block candidate: 148573 -> 149029 [Your node is 456 blocks (0 days) behind] 
SYNCHRONIZATION started
2018-03-20 11:12:34.968	[P2P5]	INFO 	global	src/cryptonote_protocol/cryptonote_protocol_handler.inl:1154	[92.14.239.76:48772 OUT]  Synced 148673/149029
2018-03-20 11:12:36.385	[P2P8]	ERROR	cn	src/cryptonote_basic/cryptonote_format_utils.cpp:972	Failed to parse block from blob
2018-03-20 11:12:39.173	[P2P5]	INFO 	global	src/cryptonote_protocol/cryptonote_protocol_handler.inl:1154	[92.14.239.76:48772 OUT]  Synced 148773/149029
2018-03-20 11:12:40.279	[P2P9]	ERROR	cn	src/cryptonote_basic/cryptonote_format_utils.cpp:972	Failed to parse block from blob
2018-03-20 11:12:43.148	[P2P5]	INFO 	global	src/cryptonote_protocol/cryptonote_protocol_handler.inl:1154	[92.14.239.76:48772 OUT]  Synced 148873/149029`

With added debug output:

`2018-03-20 11:42:18.548	[P2P1]	DEBUG	net	contrib/epee/include/net/levin_protocol_handler_async.h:401	[124.149.88.153:48772 OUT] LEVIN_PACKET_RECIEVED. [len=980580, flags1, r?=0, cmd = 2004, v=1
2018-03-20 11:42:18.549	[P2P1]	INFO 	net.p2p.msg	src/cryptonote_protocol/cryptonote_protocol_handler.inl:839	[124.149.88.153:48772 OUT] Received NOTIFY_RESPONSE_GET_OBJECTS (67 blocks, 0 txes)
2018-03-20 11:42:18.549	[P2P1]	DEBUG	net.cn	src/cryptonote_protocol/cryptonote_protocol_handler.inl:861	[124.149.88.153:48772 OUT]  downloaded 979195 bytes worth of blocks
2018-03-20 11:42:18.550	[P2P1]	ERROR	cn	src/cryptonote_basic/cryptonote_format_utils.cpp:972	Failed to parse block from blob
2018-03-20 11:42:18.550	[P2P1]	ERROR	net.cn	src/cryptonote_protocol/cryptonote_protocol_handler.inl:895	[124.149.88.153:48772 OUT] sent wrong block: failed to parse and validate block: 03003d40924626f24ba08a8d220e275f35d01baf3125eddb6abd3e064e6c797cfb4301009aadc3d505c17038a48a8f5bebfd4676d38bd0a375bc08c39843ef1b1937241956b124d872e7ad2a0001000000002303210852bed34e8c52cd9af67515d2b9c944c612afe4181c1196e42fab8692c3c4722bd6dd2c947d1855f9bdd00edeece01c6e0d122746a1dc3bd7d4962579a7598d5bd50e0abd81c78a2c75886a94d202f3e90768bb16dfdb34bd616732876121344e3c9f26a484298348ef8f718b70113c22fd1f3083acd29fe970ccc1450a37c78a22f9221c0e47bdd564261881c2f5ea86b9ac93095a7c251d1aaa42ee2097eb8b4ac2e34792966f9fd9a0ca7dd53b1fb95eb975a6f55018fd24508598e89c36e8b6985c6f065c44719d797de70dc18594c6836b84bb34323776e018f9832a9a95ee6c508fc75b4908331f09d3277f92e1d3b734779c5b17bac504c36f0d8fc5e9e95f0a428db0e8cd313cb3200b67d2f5ba1a9221f96896ac6d4f59f98d86ba7701b28c0901fff68b0908f1ca020239bd8484f70638e02e5969e91b8594fd0e38081ada0912f909ed6c1eea0adf35a0f73602dac5d592a9d73908d8d790c3e621ce2dca2b3e062ccfce857ab8745282b793ecc08db701028740fe1d774987fd3f5ff7356c159e52494ca3ae2fb3949e9342f260fde9760c8095f52a029350e49b9c37eaf2643b50a2976516f8f93d3857fc3a3232502c4d1f6f4a55138088debe01028141a58e44f3e084ef1b2a4af9c324d97d1d3097c5ee8fafebc0331dc1fa233280bcc1960b0225e023f99990fd4d7cca34f0f55be510b24a06bb87ecf265847787bf5f40fe2980a0be81950102a0f51d8c7ebffba1961079575dd7f2c53143130cf2ed2211e4b7927b55ddd87f80d0dbc3f402020e2270bc5dc9ad88dc7e96dc3daf89ef74a71a6e0226d9c8af24f7e9b03a45d02b01d39f59032244c3a4bc2d6c7bc0495afd8aaa0abb14ed2d003ed7efe1e8a658700208a79b1b862ad7830a00, dropping connection`

**Comment by BKdilse** [comment] 2018-03-20 11:55
Can confirm I am seeing "Failed to parse block from blob".  Compiled Daemon last night.  Did not delete previous block chain, just ran the new Daemon after compile.

**Comment by mannie65** [comment] 2018-03-20 12:08
I re-created the BC DB and also have the issue 

2018-03-20 12:06:01.498 [P2P8]  ERROR   cn      src/cryptonote_basic/cryptonote_format_utils.cpp:972    Failed to parse block from blob
2018-03-20 12:06:12.753 [P2P0]  ERROR   cn      src/cryptonote_basic/cryptonote_format_utils.cpp:972    Failed to parse block from blob
2018-03-20 12:06:17.362 [P2P4]  ERROR   cn      src/cryptonote_basic/cryptonote_format_utils.cpp:972    Failed to parse block from blob
2018-03-20 12:06:37.974 [P2P9]  INFO    global  src/cryptonote_protocol/cryptonote_protocol_handler.inl:305     [92.14.239.76:48772 OUT] Sync data returned a new top block candidate: 148984 -> 149052 [Your node is 68 blocks (0 days) behind]
SYNCHRONIZATION started
2018-03-20 12:06:43.989 [P2P4]  ERROR   cn      src/cryptonote_basic/cryptonote_format_utils.cpp:972    Failed to parse block from blob
2018-03-20 12:07:24.756 [P2P4]  INFO    global  src/cryptonote_protocol/cryptonote_protocol_handler.inl:305     [217.209.168.30:48772 OUT] Sync data returned a new top block candidate: 148984 -> 149053 [Your node is 69 blocks (0 days) behind]
SYNCHRONIZATION started
2018-03-20 12:07:35.842 [P2P9]  ERROR   cn      src/cryptonote_basic/cryptonote_format_utils.cpp:972    Failed to parse block from blob

**Comment by valiant1x** [comment] 2018-03-20 18:24
should be fixed in PR #51. @Venthos @BKdilse @mannie65 please test if possible.

**Comment by mannie65** [comment] 2018-03-20 18:38
@valiant1x just on a train heading  home , will test in about 40 minutes or so and report back

**Comment by BKdilse** [comment] 2018-03-20 18:41
@valiant Thanks, will test in 20mins

**Comment by BKdilse** [comment] 2018-03-20 19:23
@valiant1x  Shoudl I just be compiling as normal?

I ran the following:
cd /usr/local/src
sudo git clone https://github.com/valiant1x/intensecoin.git
cd intensecoin
sudo git checkout xmr
sudo cmake .
sudo make -j$(nproc)

started daemon, which shows:

src/daemon/main.cpp:279 Intense Coin 'XMR Rebase' (v1.44.1.0-2208264)
2018-03-20 19:18:00.742 [P2P4]  INFO    global  src/cryptonote_protocol/cryptonote_protocol_handler.inl:305     [67.84.253.44:48772 OUT] Sync data returned a new top block candidate: 146465 -> 149275 [Your node is 2810 blocks (3 days) behind]
SYNCHRONIZATION started
2018-03-20 19:18:05.915 [P2P6]  ERROR   cn      src/cryptonote_basic/cryptonote_format_utils.cpp:972    Failed to parse block from blob
2018-03-20 19:18:54.143 [P2P8]  ERROR   cn      src/cryptonote_basic/cryptonote_format_utils.cpp:972    Failed to parse block from blob
2018-03-20 19:19:07.588 [P2P6]  ERROR   cn      src/cryptonote_basic/cryptonote_format_utils.cpp:972    Failed to parse block from blob

Did I do it wrong?

**Comment by valiant1x** [comment] 2018-03-20 19:28
@BKdilse apologies, the xmr branch is outdated. Please checkout the master branch instead. Please follow the readme instructions for building (`make release`) rather than manually invoking cmake. Consider removing the `build/release/version` folder so the build tag is properly updated in the binary.

**Comment by BKdilse** [comment] 2018-03-20 19:39
@valiant1x thanks, trying again...

**Comment by mannie65** [comment] 2018-03-20 19:57
OK - recompiled from master source - started daemon and synced to latest block OK - about to start the pool and see if the 2 blocks we hit before the issue mature and are paid

**Comment by mannie65** [comment] 2018-03-20 20:07
All looking good on my pool - i'll get some hash up on it now - but so far so good, thank you for the fast turn-around.

**Comment by BKdilse** [comment] 2018-03-20 20:21
@valiant1x I can confirm all is look good for me too, and thanks for the quick fix, it saved me reverting back to 1.4.2  :)

@Venthos thanks for officially raising this, and the heads up a few days ago.  I'm back in business, with my 1 miner LOL (for now I hope).

Nice work

**Comment by uekdyr** [comment] 2018-03-20 21:15
It works, great job! :)

**Comment by podvodnik** [comment] 2018-03-21 12:08
Do the payments work now? and do you need to change the height+1 to height now for unlocker?

**Comment by marki555** [comment] 2018-03-22 08:07
Can you please make a binary daemon release with this fix?

**Comment by pallas1** [comment] 2018-03-22 08:36
Binaries available in the releases section:

https://github.com/valiant1x/intensecoin/releases

**Comment by marki555** [comment] 2018-03-22 08:44
@pallas1 In the releases section I see only version 1.45 Beta (d3d0f56) which is without 2 last commits, which fix this issue.

**Comment by pallas1** [comment] 2018-03-22 08:49
that's about the time the release was created, but the binaries have been updated since then:
"Updated 3/21/18 to include #51."

**Comment by BKdilse** [comment] 2018-03-22 08:54
I can confirm that the 1.45 Beta wallet works fine with the latest backend.

**Closed** 2018-03-31 16:47 UTC
Labels: bug
